export const redirects = JSON.parse("{}")

export const routes = Object.fromEntries([
  ["/intro.html", { loader: () => import(/* webpackChunkName: "intro.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/intro.md"), meta: {"date":1777507200000,"excerpt":"\n<img src=\"/person.jpg\" alt=\"刘荣辉\" width=\"220\">\n<h2>刘荣辉</h2>\n<p><strong>籍贯</strong>：  重庆市云阳县<br>\n<strong>生日</strong>：  2000.9<br>\n<strong>教育经历：</strong></p>\n<p>本科    西北师范大学  地理信息科学    2019-2023<br>\n硕士    西北师范大学  地图学与地理信息系统    2023-2026</p>\n","readingTime":{"minutes":0.28,"words":83},"title":"个人介绍","icon":"circle-info","type":"article"} }],
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/README.md"), meta: {"title":"小灰灰博客主页","icon":"house"} }],
  ["/demo/disable.html", { loader: () => import(/* webpackChunkName: "demo_disable.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/demo/disable.md"), meta: {"category":["使用指南"],"tag":["禁用"],"excerpt":"<p>你可以通过设置页面的 Frontmatter，在页面禁用功能与布局。</p>\n","readingTime":{"minutes":0.43,"words":128},"title":"布局与功能禁用","icon":"gears","order":4,"type":"article"} }],
  ["/demo/encrypt.html", { loader: () => import(/* webpackChunkName: "demo_encrypt.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/demo/encrypt.md"), meta: {"category":["使用指南"],"tag":["加密"],"excerpt":"\n<p>实际的文章内容。</p>\n<p>段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字。</p>\n<p>段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字。</p>\n","readingTime":{"minutes":0.51,"words":154},"title":"密码加密的文章","icon":"lock","type":"article"} }],
  ["/demo/layout.html", { loader: () => import(/* webpackChunkName: "demo_layout.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/demo/layout.md"), meta: {"category":["指南"],"tag":["布局"],"excerpt":"<p>布局包括:</p>\n<ul>\n<li><a href=\"https://theme-hope.vuejs.press/zh/guide/layout/navbar.html\" target=\"_blank\" rel=\"noopener noreferrer\">导航栏</a></li>\n<li><a href=\"https://theme-hope.vuejs.press/zh/guide/layout/sidebar.html\" target=\"_blank\" rel=\"noopener noreferrer\">侧边栏</a></li>\n<li><a href=\"https://theme-hope.vuejs.press/zh/guide/layout/footer.html\" target=\"_blank\" rel=\"noopener noreferrer\">页脚</a></li>\n</ul>","readingTime":{"minutes":0.53,"words":159},"title":"布局","icon":"object-group","order":2,"type":"article"} }],
  ["/demo/markdown.html", { loader: () => import(/* webpackChunkName: "demo_markdown.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/demo/markdown.md"), meta: {"category":["使用指南"],"tag":["Markdown"],"excerpt":"<p>VuePress 主要从 Markdown 文件生成页面。因此，你可以使用它轻松生成文档或博客站点。</p>\n<p>你需要创建并编写 Markdown，以便 VuePress 可以根据文件结构将它们转换为不同的页面。</p>\n","readingTime":{"minutes":3.13,"words":938},"title":"Markdown 展示","icon":"fa6-brands:markdown","order":2,"type":"article"} }],
  ["/demo/page.html", { loader: () => import(/* webpackChunkName: "demo_page.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/demo/page.md"), meta: {"author":"Ms.Hope","date":1577836800000,"category":["使用指南"],"tag":["页面配置","使用指南"],"sticky":true,"cover":"/assets/images/cover1.jpg","excerpt":"<p><code>more</code> 注释之前的内容被视为文章摘要。</p>\n","readingTime":{"minutes":1.76,"words":529},"title":"页面配置","icon":"file","order":3,"type":"article"} }],
  ["/demo/", { loader: () => import(/* webpackChunkName: "demo_index.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/demo/README.md"), meta: {"category":["使用指南"],"readingTime":{"minutes":0.07,"words":20},"title":"功能与配置演示","icon":"laptop-code","type":"article"} }],
  ["/posts/Python/%E9%AB%98%E5%BE%B7%E7%88%AC%E5%8F%96POI.html", { loader: () => import(/* webpackChunkName: "posts_Python_高德爬取POI.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/posts/Python/高德爬取POI.md"), meta: {"date":1640995200000,"category":["Python"],"tag":["Python","高德","POI"],"excerpt":"\n<p>这是我自己通过对网络资料的收集和自己所学的浅薄Python知识进行整理写成的高德POI获取代码方法。</p>\n<blockquote>\n<p><strong><span style=\"color:#2e8b57; font-size: 22px;\">关于高德POI</span></strong></p>\n<p>高德POI是从高德官方API接口中获取的，需要一定的代码知识基础。</p>\n</blockquote>\n<h2>⼀、获取高德API的key</h2>\n<p>首先在<a href=\"(https://lbs.amap.com/)\">⾼德开放平台</a>注册并认证,进入个人中⼼-&gt;应用管理-&gt;我的应用-&gt;创建应用-&gt;添加-&gt;<br>\n命名，服务平台选择Web服务，勾选协议许可，确定-&gt;就能看到你自己的key了。<br>\n注册并认证之后你的信息如下<br>\n<img src=\"/assets/images/gd1.png\" alt=\"高德爬取POI\" loading=\"lazy\"></p>","readingTime":{"minutes":4.33,"words":1299},"title":"高德爬取POI","icon":"pen-to-square","type":"article"} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/.vuepress/.temp/pages/404.html.vue"), meta: {"title":""} }],
  ["/posts/Python/", { loader: () => import(/* webpackChunkName: "posts_Python_index.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/.vuepress/.temp/pages/posts/Python/index.html.vue"), meta: {"title":"Python"} }],
  ["/posts/", { loader: () => import(/* webpackChunkName: "posts_index.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/.vuepress/.temp/pages/posts/index.html.vue"), meta: {"title":"Posts"} }],
  ["/category/", { loader: () => import(/* webpackChunkName: "category_index.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/.vuepress/.temp/pages/category/index.html.vue"), meta: {"title":"分类","index":false} }],
  ["/category/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/", { loader: () => import(/* webpackChunkName: "category_使用指南_index.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/.vuepress/.temp/pages/category/使用指南/index.html.vue"), meta: {"title":"使用指南 分类","index":false} }],
  ["/category/%E6%8C%87%E5%8D%97/", { loader: () => import(/* webpackChunkName: "category_指南_index.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/.vuepress/.temp/pages/category/指南/index.html.vue"), meta: {"title":"指南 分类","index":false} }],
  ["/category/python/", { loader: () => import(/* webpackChunkName: "category_python_index.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/.vuepress/.temp/pages/category/python/index.html.vue"), meta: {"title":"Python 分类","index":false} }],
  ["/tag/", { loader: () => import(/* webpackChunkName: "tag_index.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/.vuepress/.temp/pages/tag/index.html.vue"), meta: {"title":"标签","index":false} }],
  ["/tag/%E7%A6%81%E7%94%A8/", { loader: () => import(/* webpackChunkName: "tag_禁用_index.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/.vuepress/.temp/pages/tag/禁用/index.html.vue"), meta: {"title":"标签: 禁用","index":false} }],
  ["/tag/%E5%8A%A0%E5%AF%86/", { loader: () => import(/* webpackChunkName: "tag_加密_index.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/.vuepress/.temp/pages/tag/加密/index.html.vue"), meta: {"title":"标签: 加密","index":false} }],
  ["/tag/%E5%B8%83%E5%B1%80/", { loader: () => import(/* webpackChunkName: "tag_布局_index.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/.vuepress/.temp/pages/tag/布局/index.html.vue"), meta: {"title":"标签: 布局","index":false} }],
  ["/tag/markdown/", { loader: () => import(/* webpackChunkName: "tag_markdown_index.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/.vuepress/.temp/pages/tag/markdown/index.html.vue"), meta: {"title":"标签: Markdown","index":false} }],
  ["/tag/%E9%A1%B5%E9%9D%A2%E9%85%8D%E7%BD%AE/", { loader: () => import(/* webpackChunkName: "tag_页面配置_index.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/.vuepress/.temp/pages/tag/页面配置/index.html.vue"), meta: {"title":"标签: 页面配置","index":false} }],
  ["/tag/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/", { loader: () => import(/* webpackChunkName: "tag_使用指南_index.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/.vuepress/.temp/pages/tag/使用指南/index.html.vue"), meta: {"title":"标签: 使用指南","index":false} }],
  ["/tag/python/", { loader: () => import(/* webpackChunkName: "tag_python_index.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/.vuepress/.temp/pages/tag/python/index.html.vue"), meta: {"title":"标签: Python","index":false} }],
  ["/tag/%E9%AB%98%E5%BE%B7/", { loader: () => import(/* webpackChunkName: "tag_高德_index.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/.vuepress/.temp/pages/tag/高德/index.html.vue"), meta: {"title":"标签: 高德","index":false} }],
  ["/tag/poi/", { loader: () => import(/* webpackChunkName: "tag_poi_index.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/.vuepress/.temp/pages/tag/poi/index.html.vue"), meta: {"title":"标签: POI","index":false} }],
  ["/article/", { loader: () => import(/* webpackChunkName: "article_index.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/.vuepress/.temp/pages/article/index.html.vue"), meta: {"title":"文章","index":false} }],
  ["/star/", { loader: () => import(/* webpackChunkName: "star_index.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/.vuepress/.temp/pages/star/index.html.vue"), meta: {"title":"星标","index":false} }],
  ["/timeline/", { loader: () => import(/* webpackChunkName: "timeline_index.html" */"D:/Desktop/demo/Vae-Liker.github.io/src/.vuepress/.temp/pages/timeline/index.html.vue"), meta: {"title":"时间轴","index":false} }],
]);

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  __VUE_HMR_RUNTIME__.updateRoutes?.(routes)
  __VUE_HMR_RUNTIME__.updateRedirects?.(redirects)
}

if (import.meta.hot) {
  import.meta.hot.accept((m) => {
    __VUE_HMR_RUNTIME__.updateRoutes?.(m.routes)
    __VUE_HMR_RUNTIME__.updateRedirects?.(m.redirects)
  })
}
