name: Deploy GitHub Pages

on:
  # 推送到main分支时自动触发部署
  push:
    branches: [ master ]
  # 支持手动在GitHub页面触发
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 设置 pnpm
        uses: pnpm/action-setup@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          # 选择要使用的 node 版本
          node-version: 22
          # 缓存 pnpm 依赖
          cache: pnpm

      - name: 安装项目依赖
        run: pnpm install --frozen-lockfile

      - name: 构建静态站点
        run: pnpm docs:build # 和你package.json里的构建命令保持一致

      - name: 部署到 GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 你的构建产物目录，必须和实际路径一致！
          publish_dir: src/.vuepress/dist
          target_branch: gh-pages
          force_orphan: true